#spring.application.name=outdoorShop
spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/outdoorShop
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true  # H2 ? ?? ??? (http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: create
    # show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL ???

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
  #spring:
  devtools:
    restart:
      enabled: true

  thymeleaf:
    cache: false